### PR TITLE
Add Odnoklassniki button (`btn-odnoklassniki`)

### PR DESCRIPTION
**Pull request by matyunin**
Added styles and HTML markup for `index.html` according [style guides](http://v.ok.ru/logo.html).

### CODE REVIEW

**Comment by lipis** [comment]
Nice.. will merge it once I'm back :) :palm_tree:

**Comment by matyunin** [comment]
:+1:

**Comment by FractalizeR** [comment]
Ping ;)

**Comment by matyunin** [comment]
@lipis, hi! What about PR? We are waiting :)

**Comment by lipis** [comment]
According to the link you provided.. the color should be: `#f4731c`
http://v.ok.ru/images/logo/download/ok_logo_sign_orange.svg

**Comment by matyunin** [comment]
@lipis, yep... fixed in c331f9c5.

**Comment by lipis** [comment]
Can you squash the commits as well?

**Comment by matyunin** [comment]
@lipis, done!

**Comment by lipis** [comment]
:+1:

**Pull request merged**
