### PR TITLE
Added Pinterest button .btn-pinterest

### PR DESCRIPTION
**Pull request by mmulqueen**
Icon already present in Font Awesome.

### CODE REVIEW

**Comment by lipis** [comment]
I used to have it.. https://github.com/lipis/bootstrap-social/commit/8ad5c0504d86464217e73160098228b6e2a4c46d but I removed it because they don't support an official OAuth API.. It is not that hard to add new buttons and I think we have already too many.. Having said that maybe in the future I'll add it.. :D

**Comment by mmulqueen** [comment]
There are possible uses for these buttons other than authentication - for example sharing buttons, which is my use case. I know this isn't the focus of your project.

**Comment by lipis** [comment]
Yes, sharing is totally valid case.. especially for the squared ones.. So I might add it in the near future.. when I'm back from vacations..

**Comment by lipis** [comment]
https://github.com/lipis/bootstrap-social/commit/918fc55c3c938377a7618ec0f115846e50d4b883

**Pull request closed without merging**
