### PR TITLE
add windows live and openid

### PR DESCRIPTION
**Pull request by pryankster**

### CODE REVIEW

**Comment by lipis** [comment]
In one of my other projects we decided to go with [#2672ec](http://0to255.com/2672ec) for windows instead of [#0072c6](http://0to255.com/0072c6).. do you mind showing the sources of your decisions for the colors?

**Comment by lipis** [comment]
https://github.com/gae-init/gae-init-auth/pull/10

**Comment by lipis** [comment]
Oki.. I found the OpenID.. http://wiki.openid.net/f/openid-logo-guidelines.pdf

**Comment by lipis** [comment]
The `#2672ec` can also be found here: https://login.live.com

**Comment by pryankster** [comment]
went with hotmail's default UI for the color of the windows logo. 

--pry

**Comment by lipis** [comment]
I think is better to use `#2672ec` since it can be found in the official Microsoft accounts login page.. 
So if you could please make that change and also instead of `btn-windows` say it `btn-microsoft` (because it's a microsoft account and not windows) and finally put them all in alphabetical order :)

**Comment by pryankster** [comment]
I updated the color of the Live/Windows icon and renamed it to windows -- it was called 'windows' because that's the name of the fa icon, and chose it for consistency's sake.    I guess technically it's a "Windows Live" login :-)  As far as the colors for the OpenID icon, since FA doesn't do multi-color, the choice according to the OpenID style guide is white-on-black.  opinion?

**Comment by lipis** [comment]
Recently they changed it to [Microsoft Account](http://en.wikipedia.org/wiki/Microsoft_account) so that's why I also want to start using that instead of Windows.. which makes more sense if you get from the rest of the brands when trying to login with their accounts.. If it was still hotmail, that would be another story but they want to unify all these accounts into one and I think they made the right decision for the name..! Having said that I think FA should have an alias for `fa-microsoft` :)

As for the OpenID.. it looks like the guides are saying either black on white or white on black... but I still think it would be still ok with their normal color..! As with this project I also want to have the collection of their official colors...

**Comment by lipis** [comment]
But I didn't think about the consistency because it's `fa-windows`... I'll think about it and merge them tomorrow.. thanks for the PR..

**Pull request merged**
